title: Web crawler
description: >-
  Crawl the web page at a provided URL and get back a replayable WACZ file.
type: object
properties:
  site:
    title: Site
    type: string
    format: uri
    description: The URL of the site to start crawling
  # browsertrix_server:
  #   title: Browsertrix Server
  #   type: string
  #   format: uri
  #   description: The URL of the Browsertrix server
  #   default: https://org1.browsertrix.stg.starlinglab.org
required:
  - site
