name: Run Add-On
on: repository_dispatch

jobs:
  Run-Add-On:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@v1
    secrets:
      # Hack to pass in multiple secrets: encode as JSON
      token: '["${{ secrets.USERNAME }}", "${{ secrets.PASSWORD }}"]'
